[package]
name = "B1ackH0rse"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio =  { version = "1.0", features = ["full"] }
hyper = { version="0.14", features = ["full"] }
rcgen = { version="0.14.6", features = ["pem", "x509-parser"]}
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"